# Generated by Django 4.0.3 on 2022-07-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
