# Generated by Django 4.0.3 on 2022-07-09 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_postmodel_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='liked',
        ),
    ]
